# Generated by Django 3.1.3 on 2021-07-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_structuredatabase_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='fastasequence_file',
            field=models.FileField(blank=True, null=True, upload_to='fastasequence_files/'),
        ),
    ]
