# Generated by Django 3.1.3 on 2021-07-13 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20210713_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='taxonid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\d{50}$', 'Number must digits', 'Invalid number')]),
        ),
    ]
