# Generated by Django 3.1.3 on 2021-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20210713_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='taxonid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
