# Generated by Django 3.1.3 on 2021-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20210713_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='taxonid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
