# Generated by Django 3.1.3 on 2021-07-13 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20210713_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('\\d{2,50}', 'Number must digits', 'Invalid number')]),
        ),
    ]
