# Generated by Django 3.1.3 on 2021-07-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20210713_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='taxonid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
