# Generated by Django 3.1.3 on 2021-07-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20210713_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='taxonid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
