# Generated by Django 3.1.3 on 2021-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20210713_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteindetail',
            name='accession',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='cdd_C',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='cdd_M',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='cdd_N',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='domain_C',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='domain_M',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='domain_N',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='end_C',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='end_M',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='end_N',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='fulllength',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_C',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_M',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_N',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='species',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='start_C',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='start_M',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='start_N',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='taxon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
