# Generated by Django 3.1.3 on 2021-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20210802_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteindetail',
            name='fulllength',
            field=models.TextField(blank=True, null=True, verbose_name='Length of the protein sequence'),
        ),
    ]
