# Generated by Django 3.1.3 on 2021-08-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20210802_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteindetail',
            name='cdd_N',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Conserved Domain Database ID (CDD N)'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='domain_C',
            field=models.TextField(blank=True, null=True, verbose_name='C-terminal domain name'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='domain_M',
            field=models.TextField(blank=True, null=True, verbose_name='Middle domain name'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='domain_N',
            field=models.TextField(blank=True, null=True, verbose_name='N-terminal domain name'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='end_C',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Amino acid end position'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='end_M',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Amino acid end position'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='end_N',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Amino acid end position'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_N',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='PFAM ID (Pfam N)'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='start_C',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Amino acid start position'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='start_M',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Amino acid start position'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='start_N',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Amino acid start position'),
        ),
    ]
