# Generated by Django 3.1.3 on 2021-08-02 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20210802_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='digits allowed.', regex='^\\+?1?\\d{1,25}$')]),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='cdd_C',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CDD C'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='cdd_M',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CDD M'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_C',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='PFAM C'),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_M',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='PFAM M'),
        ),
    ]
