# Generated by Django 3.1.3 on 2021-08-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20210802_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='othernames',
            field=models.TextField(blank=True, null=True, verbose_name='Given name'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='othernames',
            field=models.TextField(blank=True, null=True, verbose_name='Given name'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='bacterium',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='othernames',
            field=models.TextField(blank=True, null=True, verbose_name='Given name'),
        ),
    ]
