# Generated by Django 3.1.3 on 2021-08-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20210811_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='bacterium',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='partnerprotein',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='No', null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='terms_conditions',
            field=models.BooleanField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', null=True),
        ),
    ]
