# Generated by Django 3.1.3 on 2021-08-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20210811_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='othernames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='othernames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='othernames',
            field=models.TextField(blank=True, null=True),
        ),
    ]
