# Generated by Django 3.1.3 on 2021-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20210811_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='bacterium',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='Yes', null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='partnerprotein',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='Yes', null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='terms_conditions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='Yes', null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='bacterium',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='Yes', null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='partnerprotein',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='No', null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='terms_conditions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='Yes', null=True),
        ),
    ]
