# Generated by Django 3.1.3 on 2021-08-19 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_auto_20210819_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Uploaded date'),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Uploaded date'),
        ),
    ]
