# Generated by Django 3.1.3 on 2021-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20211006_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='accession',
            field=models.CharField(max_length=25, null=True, verbose_name='ncbi accession number'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='sequence',
            field=models.TextField(null=True, verbose_name='protein sequence'),
        ),
    ]
