# Generated by Django 3.1.3 on 2021-10-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_auto_20211006_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='published',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='uploaded',
        ),
    ]
