# Generated by Django 3.1.3 on 2021-11-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_auto_20211007_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='alignresults',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='uploaded',
        ),
    ]
