# Generated by Django 3.1.3 on 2021-07-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0003_auto_20210602_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='contact_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('emailed', 'Emailed')], default='Emailed', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='contact_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('emailed', 'Emailed')], default='Emailed', max_length=10),
        ),
    ]
