# Generated by Django 3.1.3 on 2021-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0004_auto_20210726_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='User Provided Protein Name'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='User Provided Protein Name'),
        ),
    ]
