# Generated by Django 3.1.3 on 2021-11-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0006_auto_20210819_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='usersubmission',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='comment',
            new_name='user_comments',
        ),
        migrations.RenameField(
            model_name='usersubmission',
            old_name='comment',
            new_name='user_comments',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='alignresults',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='alignresults',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='name',
        ),
    ]
