# Generated by Django 3.1.3 on 2021-11-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0007_auto_20211101_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='bacterium',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='partnerprotein',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='bacterium',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='partnerprotein',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
    ]
