# Generated by Django 3.1.3 on 2021-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_alter_association_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='assay_material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='assay_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='data_entered_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='instar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='lc50',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='life_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='non_toxic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='other_citations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='target_order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='target_species',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='taxonid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='units',
            field=models.TextField(blank=True, null=True),
        ),
    ]
