# Generated by Django 3.1.3 on 2021-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_auto_20210616_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='percentage_mortality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
