# Generated by Django 3.1.3 on 2021-06-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_feedbackproteinerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdenticalProteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein1', models.CharField(blank=True, max_length=25, null=True)),
                ('protein2', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
