# Generated by Django 3.1.3 on 2021-06-29 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0012_auto_20210629_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identicalproteins',
            name='proteins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
    ]
