# Generated by Django 3.1.3 on 2021-08-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0014_auto_20210629_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'verbose_name': 'Meta database', 'verbose_name_plural': 'Metadatabase'},
        ),
    ]
