# Generated by Django 3.1.3 on 2021-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0015_auto_20210806_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutantProteinDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.TextField(blank=True, null=True)),
                ('sequence', models.TextField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
