# Generated by Django 3.1.3 on 2021-08-27 21:39

import database.storage
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0016_mutantproteindatabase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutantproteindatabase',
            options={'ordering': ('name',), 'verbose_name': 'Public Sequence', 'verbose_name_plural': 'Public Sequences'},
        ),
        migrations.RenameField(
            model_name='mutantproteindatabase',
            old_name='protein_name',
            new_name='admin_comments',
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='accession',
            field=models.CharField(max_length=25, null=True, verbose_name='NCBI accession number'),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='bacterium',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='bacterium_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutantproteindatabase_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Uploaded date'),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='dnasequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutantproteindatabase_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='edited_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Edited on'),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='fastasequence_file',
            field=models.FileField(blank=True, null=True, storage=database.storage.OverwriteStorage(), upload_to='fastasequence_files/'),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='name_category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='nontoxic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='oldname',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='othernames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='partnerprotein',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='partnerprotein_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='pdbcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='published',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='submittersemail',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='submittersname',
            field=models.CharField(blank=True, default='Uploaded by default admin user', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='digits allowed.', regex='\\d{1,25}$')]),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='terms_conditions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='toxicto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded'),
        ),
        migrations.AddField(
            model_name='mutantproteindatabase',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mutantproteindatabase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='User comments'),
        ),
        migrations.AlterField(
            model_name='mutantproteindatabase',
            name='sequence',
            field=models.TextField(null=True, verbose_name='Protein Sequence'),
        ),
    ]
