# Generated by Django 3.1.3 on 2021-09-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0017_auto_20210827_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackproteinerror',
            options={'verbose_name': 'Metadatabase Reported Protein Error', 'verbose_name_plural': 'Metadatabase Reported Protein Errors'},
        ),
        migrations.AlterModelOptions(
            name='mutantproteindatabase',
            options={'ordering': ('name',), 'verbose_name': 'Mutant Sequence', 'verbose_name_plural': 'Mutant Sequences'},
        ),
        migrations.RemoveField(
            model_name='mutantproteindatabase',
            name='fastasequence_file',
        ),
        migrations.AlterField(
            model_name='mutantproteindatabase',
            name='accession',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='NCBI accession number'),
        ),
    ]
