# Generated by Django 3.1.3 on 2021-11-05 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0018_auto_20210901_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ['name'], 'verbose_name': 'Meta database', 'verbose_name_plural': 'Metadatabase'},
        ),
        migrations.AddField(
            model_name='association',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Uploaded date'),
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Protein Name'),
        ),
    ]
