# Generated by Django 3.2 on 2022-01-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustalanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeresultfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
