# Generated by Django 3.1.3 on 2021-06-30 21:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0006_feedback_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
