# Generated by Django 3.1.3 on 2021-07-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0009_auto_20210630_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
