# Generated by Django 3.1.3 on 2021-07-01 20:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0010_auto_20210701_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
