# Generated by Django 3.1.3 on 2021-07-12 15:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0011_auto_20210701_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Add FAQ',
                'verbose_name_plural': 'Add FAQs',
                'ordering': ('question',),
            },
        ),
    ]
