# Generated by Django 3.1.3 on 2021-07-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0012_faqedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Help',
            },
        ),
    ]
