# Generated by Django 3.1.3 on 2021-07-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0013_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqedit',
            name='heading',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('emailed', 'Emailed')], default='Pending', max_length=10),
        ),
    ]
