# Generated by Django 3.1.3 on 2021-07-26 15:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0014_auto_20210726_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqedit',
            name='heading',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
