# Generated by Django 3.1.3 on 2021-07-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0015_auto_20210726_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqedit',
            name='heading',
        ),
        migrations.CreateModel(
            name='FaqEditHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra.faqedit')),
            ],
        ),
    ]
