# Generated by Django 3.1.3 on 2021-07-28 15:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0016_auto_20210728_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqedit',
            options={'ordering': ('question',), 'verbose_name': 'Add FAQ Q&A', 'verbose_name_plural': 'Add FAQ Q&As'},
        ),
        migrations.AlterModelOptions(
            name='faqeditheading',
            options={'ordering': ('heading',), 'verbose_name': 'Add FAQ Heading', 'verbose_name_plural': 'Add FAQ Headings'},
        ),
        migrations.AddField(
            model_name='faqedit',
            name='heading',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='None'),
        ),
    ]
