# Generated by Django 3.1.3 on 2021-07-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0017_auto_20210728_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqeditheading',
            options={'ordering': ('category',), 'verbose_name': 'Add FAQ Heading', 'verbose_name_plural': 'Add FAQ Headings'},
        ),
        migrations.RenameField(
            model_name='faqeditheading',
            old_name='heading',
            new_name='category',
        ),
    ]
