# Generated by Django 3.1.3 on 2021-07-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0018_auto_20210728_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqeditheading',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='extra.faqedit'),
        ),
    ]
