# Generated by Django 3.1.3 on 2021-11-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0021_auto_20210806_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncbiavailability',
            options={'verbose_name': 'NCBI accession public availability', 'verbose_name_plural': 'NCBI accession public availability'},
        ),
    ]
